import json
import subprocess
import sys
from pathlib import Path
from typing import Callable


PROJECT_ROOT = Path(__file__).resolve().parent.parent

NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"
CONFIG_DIR = PROJECT_ROOT / "data" / "raw"
OUTPUT_DIR = PROJECT_ROOT / "data" / "output"

USER_INPUT_PATH = CONFIG_DIR / "user_input.json"
FINAL_REPORT_PATH = OUTPUT_DIR / "final_report.json"

NOTEBOOKS = [
    "00_query_builder_agent.ipynb",
    "01_search_agent.ipynb",
    "02_analyst_agent.ipynb",
    "03_reviewer_agent.ipynb",
    "04_editor_agent.ipynb",
]


def run_notebook(notebook_name: str) -> None:
    """
    Execute one notebook and save its outputs in place.
    """

    notebook_path = NOTEBOOKS_DIR / notebook_name

    if not notebook_path.exists():
        raise FileNotFoundError(
            f"Notebook not found: {notebook_path}"
        )

    command = [
        sys.executable,
        "-m",
        "jupyter",
        "nbconvert",
        "--to",
        "notebook",
        "--execute",
        "--inplace",
        "--ExecutePreprocessor.timeout=600",
        notebook_name,
    ]

    result = subprocess.run(
        command,
        cwd=NOTEBOOKS_DIR,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Error executing {notebook_name}\n\n"
            f"{result.stderr}"
        )


def run_pipeline(
    research_topic: str,
    progress_callback: Callable[[int, str], None] | None = None,
) -> dict:
    """
    Execute the complete agentic research pipeline.

    Parameters
    ----------
    research_topic:
        Topic entered by the user.

    progress_callback:
        Optional function used to communicate progress.
        It receives the completion percentage and a message.

    Returns
    -------
    dict
        Final report generated by the Editor Agent.
    """

    research_topic = research_topic.strip()

    if not research_topic:
        raise ValueError("Research topic cannot be empty.")

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    user_input = {
        "research_topic": research_topic,
    }

    with USER_INPUT_PATH.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            user_input,
            file,
            indent=4,
            ensure_ascii=False,
        )

    total_notebooks = len(NOTEBOOKS)

    for index, notebook_name in enumerate(NOTEBOOKS):

        if progress_callback is not None:
            progress_callback(
                int(index / total_notebooks * 100),
                f"Running {notebook_name}",
            )

        run_notebook(notebook_name)

    if not FINAL_REPORT_PATH.exists():
        raise FileNotFoundError(
            "The pipeline finished, but final_report.json "
            "was not generated."
        )

    with FINAL_REPORT_PATH.open(
        encoding="utf-8",
    ) as file:
        final_report = json.load(file)

    if progress_callback is not None:
        progress_callback(
            100,
            "Research completed successfully",
        )

    return final_report